name: Compress images

permissions:
  contents: write
  pull-requests: write   # leave even though you’re on push

on:
  push:
    branches: [main]

jobs:
  optimise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true            # <- **required** when you call it from push
          jpegQuality: 75
          pngQuality: 75
